name: Build and Deploy to Nosana

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/neurocoder-ai:latest
            ${{ secrets.DOCKER_USERNAME }}/neurocoder-ai:v1.0
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image info
        run: |
          echo "✅ Docker image built successfully!"
          echo "📦 Image: ${{ secrets.DOCKER_USERNAME }}/neurocoder-ai:latest"
          echo ""
          echo "🚀 Next steps:"
          echo "1. Go to https://dashboard.nosana.com/deploy"
          echo "2. Use image: ${{ secrets.DOCKER_USERNAME }}/neurocoder-ai:latest"
          echo "3. Select GPU and deploy!"
